#
# GNUmakefile for target NSDiffableDataSource_test
# begin - generated by buildtool, please don't modify
#

include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = NSDiffableDataSource_test

NSDiffableDataSource_test_OBJC_FILES = NSDiffableDataSource_test/main.m \
	NSDiffableDataSource_test/AppDelegate.m 

NSDiffableDataSource_test_RESOURCE_FILES = NSDiffableDataSource_test/Base.lproj/MainMenu.xib \
	NSDiffableDataSource_test/Assets.xcassets \
	NSDiffableDataSource_testInfo.plist 

ADDITIONAL_INCLUDE_DIRS += -I. \
	-I./NSDiffableDataSource_test 

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/common.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble

#
# end - generated makefile
#
